yes|apt install mesa
yes|apt install mesa-dev
yes|apt install mesa-vulkan-icd-freedreno
yes|apt install mesa-vulkan-icd-freedreno-dri3
yes|apt install mesa-vulkan-icd-swrast
yes|apt install osmesa
yes|apt install glu
yes|apt install mesa-demos
yes|apt install osmesa-demos
