apt -y upgrade 
apt -y upgrade apt
apt -y upgrade bash
apt -y upgrade ca-certificates
apt -y upgrade command-not-found
apt -y upgrade coreutils
apt -y upgrade curl
apt -y upgrade dash
apt -y upgrade debianutils
apt -y upgrade dialog
apt -y upgrade diffutils
apt -y upgrade dos2unix
apt -y upgrade dpkg
apt -y upgrade ed
apt -y upgrade findutils
apt -y upgrade gawk
apt -y upgrade gpgv
apt -y upgrade grep
apt -y upgrade gzip
apt -y upgrade inetutils
apt -y upgrade less
apt -y upgrade libandroid-support
apt -y upgrade libassuan
apt -y upgrade libassuan
apt -y upgrade libcap-ng
apt -y upgrade libcrypt
apt -y upgrade libcurl
apt -y upgrade libevent
apt -y upgrade libexpat
apt -y upgrade libgcrypt
apt -y upgrade libgmp
apt -y upgrade libgnutls
apt -y upgrade libgpg-error
apt -y upgrade libiconv
apt -y upgrade libidn2
apt -y upgrade liblz4
apt -y upgrade liblzma
apt -y upgrade libmpfr
apt -y upgrade libnettle
apt -y upgrade libnghttp2
apt -y upgrade libnpth
apt -y upgrade libssh2
apt -y upgrade libtirpc
apt -y upgrade libunistring
apt -y upgrade lsof
apt -y upgrade nano
apt -y upgrade ncurses
apt -y upgrade openssl
apt -y upgrade pcre2
apt -y upgrade procps
apt -y upgrade psmisc
apt -y upgrade readline
apt -y upgrade sed
apt -y upgrade tar
apt -y upgrade termux-am-socket
apt -y upgrade termux-am
apt -y upgrade termux-exec
apt -y upgrade termux-keyring
apt -y upgrade termux-licenses
apt -y upgrade termux-tools
apt -y upgrade unbound
apt -y upgrade unzip
apt -y upgrade util-linux
apt -y upgrade xxhash
apt -y upgrade xz-utils
apt -y upgrade zlib
